apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    speedtest.io.service: grafana
status:
  loadBalancer: {}
