apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
