apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    speedtest.io.service: grafana
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        speedtest.io.service: grafana
    spec:
      containers:
        - env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "{{ .Values.grafana.authAnonymousEnabled }}"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.securityAdminPassword }}
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.securityAdminUser }}
            - name: GF_USERS_ALLOW_ORG_CREATE
              value: "{{ .Values.grafana.usersAllowOrgCreate }}"
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "{{ .Values.grafana.usersAllowSignUp }}"
          image: grafana/grafana:{{ .Values.grafana.version }}
          name: grafana
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana
      restartPolicy: Always
      volumes:
        - name: grafana
          persistentVolumeClaim:
            claimName: grafana
status: {}
