apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-setup
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      initContainers:
        - name: init-wait
          image: alpine
          command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 graphite 8080 && exit 0 || sleep 3; done; exit 1"]
      containers:
        - env:
            - name: GF_PASSWORD
              value: hdeAga76VG6ga7plZ1
            - name: GF_USER
              value: sitespeedio
          image: sitespeedio/grafana-bootstrap:8.8.0
          name: grafana-setup
          resources: {}
      restartPolicy: OnFailure
status: {}
