apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-setup
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      initContainers:
        - name: init-wait
          image: alpine
          command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 graphite 80 && exit 0 || sleep 3; done; exit 1"]
      containers:
        - env:
            - name: GF_PASSWORD
              value: {{ .Values.grafana.securityAdminPassword }}
            - name: GF_USER
              value: {{ .Values.grafana.securityAdminUser }}
          image: sitespeedio/grafana-bootstrap:{{ .Values.grafanaBootstrap.version }}
          name: grafana-setup
          resources: {}
      restartPolicy: OnFailure
status: {}
