apiVersion: v1
kind: Service
metadata:
  name: graphite
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "2003"
      port: 2003
      targetPort: 2003
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    speedtest.io.service: graphite
status:
  loadBalancer: {}
