apiVersion: batch/v1beta1
kind: CronJob
metadata:
metadata:
  name: sitespeed-io
  namespace: {{ .Values.namespace }}
spec:
  schedule: "{{ .Values.sitespeed.cron }}"
  jobTemplate:
    spec:
      replicas: 1
      strategy:
        type: Recreate
      template:
        spec:
          containers:
            - args:
                - -V
              image: sitespeedio/sitespeed.io
              name: sitespeed-io
              args:
              - /sitespeed.io/urls.txt
              - --graphite.host=graphite
              resources: {}
              volumeMounts:
                - mountPath: /sitespeed.io/sitespeed-result
                  name: sitespeed-io-claim
                - mountPath: /sitespeed.io/urls.txt
                  subPath: urls.txt
                  name: sitespeed-io-configmap                  
          restartPolicy: OnFailure
          volumes:
            - name: sitespeed-io-claim
              persistentVolumeClaim:
                claimName: sitespeed-io
            - name: sitespeed-io-configmap
              configMap:
                name: sitespeed-io-configmap
                items:
                  - key: urls.txt
                    path: urls.txt                
status: {}
