apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sitespeed-io
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
